default: &default
  adapter: postgresql
  encoding: utf8
  pool: 20


development:
  <<: *default
  database: grail_app_dev

test: &test
  <<: *default
  database: grail_app_test


production:
  <<: *default
  database: grail_app_prod
