default: &default
  adapter: postgresql
  encoding: utf8
  pool: 20


development:
  <<: *default
  database: grail_appdev

test: &test
  <<: *default
  database: grail_apptest


production:
  <<: *default
  database: grail_appprod
